# Generated by Django 2.2 on 2020-04-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='登録ユーザ')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新ユーザ')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('url', models.URLField(max_length=1024, null=True, verbose_name='URL')),
                ('website_name', models.CharField(max_length=1024, null=True, verbose_name='WEBサイト名称')),
                ('page_name', models.CharField(max_length=1024, null=True, verbose_name='ページ名称')),
            ],
            options={
                'db_table': 'scraping_result',
            },
        ),
    ]
