# Generated by Django 2.2 on 2020-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20200430_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingimage',
            name='full_image',
            field=models.ImageField(height_field='full_height', max_length=1024, upload_to='scraping/', verbose_name='フルサイズ画像ファイル', width_field='full_width'),
        ),
    ]
